# Estadistica Aplicada

Sesión 3, 10ago

Ricardo de Jesús Cervantes García 1958971

Numpy (Numerical python) ayuda a manejar números en python

La estructura básica de Numpy son los arreglos
Un arreglo es una collección de objetos del mismo tipo

Vamos a suponer que tenemos las ventas de botellas de agua de la cafetría de la facu

Lunes 23, martes 45, miércoles 34, jueves 28, viernes 20

In [1]:
import numpy as np

In [2]:
ventas=[23,45,34,28,20]

In [6]:
type(ventas)

numpy.ndarray

In [5]:
ventas=np.array(ventas)

In [7]:
np.sum(ventas)

150

In [8]:
np.prod(ventas)

19706400

In [9]:
np.mean(ventas)

30.0

In [10]:
np.max(ventas)

45

In [11]:
np.min(ventas)

20

In [21]:
np.sort(ventas)

array([20, 23, 28, 34, 45])

In [17]:
np.var(ventas)
np.var(ventas,ddof=1)

87.55555555555556

In [18]:
np.std(ventas)
np.std(ventas, ddof=1)

9.924716620639604

In [24]:
# vector
np.arange(9,18,2)

array([ 9, 11, 13, 15, 17])

In [35]:
np.random.seed(12)
np.random.randint(0,25,10)

array([11,  6, 17,  2,  3,  3, 12, 16, 22, 17])